### ISSUE TITLE
Create and add dapp console upsell modal

### ISSUE THREAD

**Issue by tarunkhasnavis** [ethereum-optimism/ecosystem#146]
![Screenshot 2024-03-05 at 2 05 41 PM](https://github.com/ethereum-optimism/ecosystem/assets/7953225/0da2bba5-d3a5-48c7-a6b0-5d64a88c8b1e)

**Comment by shaunop** [comment]
Here's the image, lmk if you need different size: 
<img width="820" alt="Superchain Dev Preview" src="https://github.com/ethereum-optimism/ecosystem/assets/140648764/5519d16c-06fc-4734-a775-e1210ed6a1b2">

**Comment by shaunop** [comment]
@tarunkhasnavis Updated this image to account for new "Superchain" logo. 

<img width="800" alt="Superchain Dev Preview" src="https://github.com/ethereum-optimism/ecosystem/assets/140648764/9c3267d6-2df3-4b06-9e0c-2b9cf76c26a7">
