### ISSUE TITLE
Multichain Faucet Claim Flow

### ISSUE THREAD

**Issue by fainashalts** [ethereum-optimism/ecosystem#509]
As an initial push to help developers receive funds for multiple testnets at once, we need to provide a claim flow that allows redistribution of funds through a multibridge approach.

**Comment by mayanksayshi** [comment]
Hey @fainashalts  I wanted to clarify a few things. It’s not entirely clear to me what specific updates are needed for the flow. Could you provide more granular details or specific requirements?

**Comment by jvmi7** [comment]
As a starter, we have a few options here:

- Add a UI change that is a modal which describes to the user that they can claim to sepolia and then use superchain.tools/bridge in order to distribute the funds
- Potentially use multicall in order to write a subsequent transaction after bridging to allow the user to bridge the funds on multiple networks after claiming
- Add functionality to our backend in order to enable users to claim on multiple chains at once

cc @mayanksayshi lmk if this makes sense

**Comment by fainashalts** [comment]
@jvmi7 @mayanksayshi have you made a decision on the path forward here? I think multicall is what was discussed originally as a way to smooth this out for users, and so we can punt the backend changes to a broader redesign of the faucet. Curious what @tremarkley thinks as well. If this is already decided/underway please link to the PR so we can have a source of truth here for this task. Thank you!

**Comment by mayanksayshi** [comment]
Hey @fainashalts, I had a sync with @pharger @jvmi7 @tarunkhasnavis. Please see the meeting notes. 

### Key Points from Faucet Backend Sync:

1. **Multicall Implementation**:
   - The multicall approach is confirmed and optimized for gas costs.
   - This allows users to bridge ETH to multiple networks after claiming on Sepolia.
   - The current solution is a temporary fix leading up to DevCon, with plans to update the backend post-DevCon for more seamless multichain claims.

2. **Gas Optimization**:
   - The multicall setup is gas-optimized, though users will incur a small fee (~0.003 ETH per bridge transaction).
   - For DevCon, this setup should suffice for developers to get started.

3. **User Experience**:
   - The flow simplifies claiming ETH on Sepolia and bridging to multiple networks in a single transaction.
   - A single button will handle the multicall bridge, with atomic transactions to manage failures.

4. **Backend Improvements Post-DevCon**:
   - The current implementation is temporary, and a more robust backend solution for multichain deposits will be implemented after DevCon.


Link to work in progress figma file: https://www.figma.com/design/rBlLeciYg1jJBUDYmtjzr0/%F0%9F%9A%B0-Superchain-Faucet---Multichain-Support?node-id=4221-69614

**Comment by mayanksayshi** [comment]
@fainashalts @pharger @jvmi7 @tarunkhasnavis  here is the link to the latest Figma design

https://www.figma.com/design/rBlLeciYg1jJBUDYmtjzr0/%F0%9F%9A%B0-Superchain-Faucet---Multichain-Support?node-id=4237-101085

If you can review it today and provide your feedback, I can apply the changes and have it ready for the developer handover by tomorrow. :)

**Comment by mayanksayshi** [comment]
@jvmi7 

- [ ] could we make this interaction smoother? When the user selects the second network, it would be great if the banner appeared more seamlessly.

https://github.com/user-attachments/assets/b83fcae5-57e9-474f-9e2e-749ca903e1d4


- [ ] The colour for the banner does not match the designs in Figma 

Currrent Implementation: 
![image](https://github.com/user-attachments/assets/d2a077c1-8660-4b03-bc88-36f087649aa2)


Figma:
![image](https://github.com/user-attachments/assets/340ea907-ddbb-477c-ad6a-c302c4d050b8)

Link to [figma](https://www.figma.com/design/rBlLeciYg1jJBUDYmtjzr0/%F0%9F%9A%B0-Faucet-with-Multichain-Support?node-id=4237-102212&t=w4uBKQ2IyQlzqhAN-4)

**Comment by mayanksayshi** [comment]
@jvmi7, 

- [ ] we currently show the confetti animation when ETH is claimed to Ethereum Sepolia, which might be a bit misleading. Could we trigger the animation only after the funds have been successfully bridged to the selected networks instead?

**Comment by mayanksayshi** [comment]
@jvmi7, 

I noticed that the switch network button and the bridge button differ in size and position, with the switch network button being smaller. Could we make them the same size (large) and align them to the same position for consistency?

https://github.com/user-attachments/assets/c9a877ba-0388-48e1-80ac-cb6e7c7d3144

**Comment by mayanksayshi** [comment]
@jvmi7

- [ ] Please include "Faucet" in the top navigation bar. Is this on your side, or Tarun 

Figma
![image](https://github.com/user-attachments/assets/fcc6abad-b769-4892-b7ad-149e33ef47cb)

**Comment by mayanksayshi** [comment]
@jvmi7 

- [ ] The button copy should be "Claim 0.1 ETH on n networks"

![image](https://github.com/user-attachments/assets/e8a89cd9-1b19-4eba-8b70-e0af362f4f49)

**Comment by mayanksayshi** [comment]
@jvmi7 

- [ ] I can not proceed further. I am stuck at this; the button is disabled. 

![image](https://github.com/user-attachments/assets/dcdc7b8f-a30a-40dc-836b-7dc4dc73a793)

**Comment by mayanksayshi** [comment]
@jvmi7  

Please add a ghost button hover state to the icon. 

![image](https://github.com/user-attachments/assets/b0dcce8d-9f3d-4172-bd15-00cc8c72bc28)

**Comment by jvmi7** [comment]
> @jvmi7
> 
> * [ ]  The button copy should be "Claim 0.1 ETH on n networks"
> 
> ![image](https://private-user-images.githubusercontent.com/177021070/383280027-e8a89cd9-1b19-4eba-8b70-e0af362f4f49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NDU2MjAsIm5iZiI6MTczMDg0NTMyMCwicGF0aCI6Ii8xNzcwMjEwNzAvMzgzMjgwMDI3LWU4YTg5Y2Q5LTFiMTktNGViYS04YjcwLWUwYWYzNjJmNGY0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQyMjIyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2YyM2U1OTM1NzY2NzQzM2Q4MDg0NWI2NWE0NzE3YWE4MzZmNjEzODdmYzM2ZDVlMjYyZDljYTdhZGY0N2QwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.f0Mw0KQlaRoZJu7o9qN7iMGxTAonILfU7arPxHGT9y0)

Do you think saying 0.1 ETH on N networks is misleading? When i read that I think that I'll be getting 0.1 ETH on each network. Calculating the amount of ETH you will receive on each network based on the number of networks selected made more sense to me. @mayanksayshi

**Comment by mayanksayshi** [comment]
> > @jvmi7
> > 
> > * [ ]   The button copy should be "Claim 0.1 ETH on n networks"
> > 
> > ![image](https://private-user-images.githubusercontent.com/177021070/383280027-e8a89cd9-1b19-4eba-8b70-e0af362f4f49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NDU2MjAsIm5iZiI6MTczMDg0NTMyMCwicGF0aCI6Ii8xNzcwMjEwNzAvMzgzMjgwMDI3LWU4YTg5Y2Q5LTFiMTktNGViYS04YjcwLWUwYWYzNjJmNGY0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQyMjIyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2YyM2U1OTM1NzY2NzQzM2Q4MDg0NWI2NWE0NzE3YWE4MzZmNjEzODdmYzM2ZDVlMjYyZDljYTdhZGY0N2QwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.f0Mw0KQlaRoZJu7o9qN7iMGxTAonILfU7arPxHGT9y0)
> 
> Do you think saying 0.1 ETH on N networks is misleading? When i read that I think that I'll be getting 0.1 ETH on each network. Calculating the amount of ETH you will receive on each network based on the number of networks selected made more sense to me. @mayanksayshi

@jvmi7 you are right lets stick with you solution :)

**Comment by fainashalts** [comment]
This initial issue is finished, with work continuing in #572.
