### ISSUE TITLE
Multichain faucet support Eng Tracking

### ISSUE THREAD

**Issue by jvmi7** [ethereum-optimism/ecosystem#530]
# Overview

This will serve as the engineering tracking issue for the Multichain faucet support we will implement before Devcon 2024.
Parent issue here: https://github.com/ethereum-optimism/ecosystem/issues/509

Figma file: https://www.figma.com/design/rBlLeciYg1jJBUDYmtjzr0/%F0%9F%9A%B0-Faucet-with-Multichain-Support?node-id=4237-101085&node-type=canvas&t=2rMHTIfpwA0tU2Pk-0

## Eng Issues
- [x] #531
- [x] #532
- [x] #533
- [x] #534
- [x] #535
- [x] #536
- [x] #537 
- [x] #556
- [x] #553
- [x] #559
- [x] #551
- [x] #561
- [x] #558
- [x] #560
- [x] #570

**Comment by fainashalts** [comment]
Closing as the tasks here are done. Thanks!
