### ISSUE TITLE
Eng Tracking: Dev Console SuperchainERC20 Support

### ISSUE THREAD

**Issue by tarunkhasnavis** [ethereum-optimism/ecosystem#542]
# Overview

This will serve as the engineering tracking issue for SuperchainERC20 Support on Dev Console. We will implement this before Devcon 2024.

Parent issue here: https://github.com/ethereum-optimism/ecosystem/issues/505

- [x] #543
- [x] #544
- [x] #545
- [x] #546
- [x] #547
- [x] #548
- [x] #554
- [x] #555
- [x] #552
- [x] #562
- [x] #564
- [x] #565
- [x] #566
- [x] #567
- [x] #563

**Comment by fainashalts** [comment]
@tarunkhasnavis I think this can be closed so I'm closing it now but feel free to reopen if needed!
