### ISSUE TITLE
Dapp Console Frontend Eng Tracking

### ISSUE THREAD

**Issue by jvmi7** [ethereum-optimism/ecosystem#74]
# Overview
This issue will serve as the parent issue for tracking all of the frontend work in the Dapp Console project.

# Breakdown
The team has opted to ship the Dapp Console in multiple phases. For now we will be focusing on the first iteration of the project (without the backend), designs for this can be found here: https://www.figma.com/file/8OsKnr7Xp6UZ1zEtiyRQek/Dapp-Console-(ShadCN)?node-id=292%3A43019&mode=dev

# Frontend eng issues
### MS1: Skeleton app with sign in/sign up flow
- [x] #75
- [x] #76
- [x] #77
- [x] #78
- [x] #80
- [x] #79
- [x] #81
- [x] #82

### MS2: Console Home UI
- [x] #83
- [x] #84
- [x] #85
- [x] #86
- [x] #87
- [x] #88
- [x] #89
- [x] #90

### MS3: About offers (modals)
- [x] #91
- [x] #92
- [x] #93
- [x] #94
- [x] #95
- [ ] #164

### MS5: Faucet changes
- [x] #152
- [x] #153
- [x] #150
- [x] #148
- [x] #146
- [x] #157
- [x] #165
- [x] #149
- [x] #173
- [x] #174

### MS6: Testing & Tracking
- [x] #103
- [x] #104
- [ ] #128
- [ ] #168

### Other
- [x] https://github.com/ethereum-optimism/ecopod/issues/867

## Bug report issues
- [x] https://github.com/ethereum-optimism/ecopod/issues/843

**Comment by imranjami** [comment]
current work remaining:
[xs] - 5
[s] - 17
[m] - 2
=25.5 working days

**Comment by zainbacchus** [comment]
Can you please add a section to faucet?

**Comment by tarunkhasnavis** [comment]
Would be good to scope and flesh out Faucet & Mixpanel (Tracking) changes. I can help with that 

Maybe we all can sync on this @imranjami @zainbacchus

**Comment by tarunkhasnavis** [comment]
Bugbash Bugs also here: https://www.notion.so/oplabs/Dapp-Console-MS1-Bugbash-de83cf2315bd4fd28afa20b65ad98ef8
